accounts/urls.py
from django.urls import include, path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('logout/', views.loginPage, name='login'),
    path('login/', views.logoutUser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),

]

equipement/urls.py
from django.urls import path
from . import views
from .views import EquipementDeleteView

app_name='equipement'

urlpatterns = [
    path('',views.home,name='home'),
    path('table/',views.table_equipement,name='table_equipement'),

    #equipement
    path('add_equipement/' ,views.EquipementCreate,  name='add_equipement'),
    path('detail_equipement/<int:equipement_id>/', views.EquipementDetail, name='detail_equipement'),
    path('update_equipement/<int:equipement_id>/update', views.EquipementUpdate, name='update_equipement'),
    # path('update_equipement/slug:pk>/update', views.PostUpdateView.as_view(), name='update_equipement'),
    path('detail_equipement/<int:equipement_id>/delete/', views.EquipementDeleteView, name='delete_equipement'),
    # path('detail_equipement/<slug:pk>/delete/', EquipementDeleteView.as_view(), name='delete_equipement'),
    # fin equipement

    #categorie
    path('category_table/', views.category_table, name='category_table'),
    path('add_categorie/', views.CategorietCreate, name='add_categorie'),
    path('update_categorie/<int:categorie_id>/update', views.CategoryUpdate, name='update_categorie'),

    #direction
    path('add_direction/', views.DirectionCreate, name='add_direction'),
    path('update_direction/<int:direction_id>/update', views.DirectionUpdate, name='update_direction'),

    path('table_user', views.tableuser, name='table_user'),

]

installation/urls.py
from django.urls import path
from . import views
from .views import InstallationDeleteView

app_name='installation'

urlpatterns = [
    path('table_installation/',views.table_installation,name='table_installation'),
    path('install/',views.InstallationCreate,name='add_install'),
    path('detail_installation/<int:installation_id>/', views.InstallationDetail, name='detail_installation'),
    # path('detail_installation/<slug:pk>/delete/', InstallationDeleteView.as_view(), name='delete_installation'),
    path('update_installation/<int:installation_id>/update', views.InstallationUpdate, name='update_installation'),
    path('detail_installation/<int:installation_id>/delete/', views.InstallationDeleteView, name='delete_installation'),
    #suive service
    path('update_service/<int:service_id>/update', views.ServiceUpdate, name='update_service'),



]

project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings




urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('admin/', admin.site.urls),
    path('', include('equipement.urls',namespace='equip')),
    path('', include('installation.urls',namespace='install')),
    
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipement/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse




# Create your models here.


EQUIPEMENT_ETAT=(
    ('0','Non attribut'),
    ('1','Attribué'),
)

class Equipement(models.Model):
    num_serie=models.CharField(max_length=20)
    nom=models.CharField(max_length=20)
    date_ajoute=models.DateTimeField(null=False,blank=False)
    etat_equipement = models.CharField(max_length=15, choices=EQUIPEMENT_ETAT,default='0',verbose_name='etat')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='categoryE')
    author = models.ForeignKey(User, on_delete=models.CASCADE)


    def get_absolute_url(self):
        # return '/detail/{}'.format(self.pk)
        return reverse('equip:detail_equipement', args=[self.pk])
        # return reverse('equip:add_equipement')


    def __str__(self):
        return self.num_serie





class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name="Nom Du Categorie")

    def __str__(self):
        return self.name

equipement/forms.py
from django import forms

from installation.models import Direction, Installation
from .models import Equipement, Category
from  django.forms import DateInput


class DateInput(forms.DateInput):
    input_type = 'date'

class EquipementForm(forms.ModelForm):

    class Meta:
        model = Equipement
        fields = ['num_serie','nom','date_ajoute','category']
        widgets={
            'date_ajoute':DateInput()
        }

    def clean_num_serie(self):
        cd = self.cleaned_data
        if(Equipement.objects.filter(num_serie=cd['num_serie']).exists()):
            raise forms.ValidationError(f"Numero Serie { cd['num_serie']}  existe deja ")
        return cd['num_serie']



class EquipementFormm(forms.ModelForm):

    class Meta:
        model = Equipement
        fields = ['num_serie','nom','date_ajoute','category']
        widgets = {
            'date_ajoute': DateInput()
        }






class AtributForm(forms.ModelForm):

    class Meta:
        model = Equipement
        fields = ['etat_equipement']

#datil equipement deja installer
class EquipInstall(forms.ModelForm):
    class Meta:
        model = Installation
        fields = ['ip', 'mac','date_installe','Nom_direction']
        widgets = {
            'date_installe': DateInput()
        }

    def clean_ip(self):
        cd = self.cleaned_data
        if (Installation.objects.filter(ip=cd['ip']).exists()):
            raise forms.ValidationError(f" Ip {cd['ip']}   deja existe ")
        return cd['ip']


    def clean_mac(self):
        cd = self.cleaned_data
        if (Installation.objects.filter(mac=cd['mac']).exists()):
            raise forms.ValidationError(f" Adresse mac {cd['mac']}   deja existe ")
        return cd['mac']


#form add_categorie_equipement
class CategorieForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name',]

    def clean_name(self):
        cd = self.cleaned_data
        if (Category.objects.filter(name=cd['name']).exists()):
            raise forms.ValidationError(f"La categorie { cd['name']}   deja existe ")
        return cd['name']


#form add_direction
class DirectionForm(forms.ModelForm):

    class Meta:
        model = Direction
        fields = ['Nom']

    def clean_Nom(self):
        cd = self.cleaned_data
        if (Direction.objects.filter(Nom=cd['Nom']).exists()):
            raise forms.ValidationError(f"Cet nom direction  {cd['Nom']} deja existe ")
        return cd['Nom']





    # class CategoryForm(forms.ModelForm):
#     class Meta:
#         model = Category
#         fields = ['name',]

equipement/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404
from mathfilters.templatetags.mathfilters import sub

from accounts.decorators import allowed_users
from accounts.models import Profile
from installation.models import Direction, Installation
from .filter import EquipementFilter
from .models import Equipement, Category
from django.contrib.auth.decorators import login_required
from .forms import EquipementForm, CategorieForm, DirectionForm, EquipInstall, AtributForm, EquipementFormm


# Create your views here.
# def cal(n1,n2):
#     z=5|sub:7
#     return z
#index.html page principale
@login_required(login_url='accounts/login')
def home(request):
    list_quip=Equipement.objects.all()
    list_installation = Installation.objects.all()
    list_direction = Direction.objects.all()
    list_dir = Direction.objects.all()
    list_category = Category.objects.all()
    # detail_installation = get_object_or_404(Installation, pk=Installation.id)
    equipement_service= Installation.objects.filter(service='En service')
    # inst = Installation.objects.filter(equipement_installe=Equipement.categoryE)
    equipement_panne = Installation.objects.filter(service='En panne')
    profile = Profile.objects.all()
    user = User.objects.all()



    paginator = Paginator(list_direction, 3)
    page_numbre = request.GET.get('page')
    page_obj = paginator.get_page(page_numbre)
    context={
       'title':'Accueil',
        # 'inst':inst,
        'list_quip': list_quip,
        'list_installation':list_installation,
        'list_direction':page_obj,
        'equipement_service':equipement_service,
        'equipement_panne':equipement_panne,
        'profile': profile,
        'user': user,
        'list_category':list_category,
        'list_dir':list_dir,

    }
    return render(request,'equipement/index.html',context)


@login_required(login_url='accounts/login')
def tableuser(request):
    profile = Profile.objects.all()
    user = User.objects.all()

    # n= Equipement.objects.all().count|sub-Installation.objects.all().count


    context={

        'profile': profile,
        'user': user

    }
    return render(request,'equipement/table_user.html',context)





# ajoute un equipement
@login_required(login_url='accounts/login')

def EquipementCreate(request):
    if request.method == 'POST':
        form = EquipementForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.author = request.user
            myform.save()
            messages.success(
                request, f"L'equipemet du numero  {myform.num_serie} est bien ajoute")
            return redirect(reverse('equip:add_equipement'))
        else:
            messages.error(request, "Un erreur se produire")
    else:
        form = EquipementForm()

    return render(request, 'equipement/add_equipement.html', {'form': form})



#afficher info d'equipement
@login_required(login_url='accounts/login')
def EquipementDetail(request, equipement_id):
    equipement_installe= get_object_or_404(Equipement, pk=equipement_id)
    inst= Installation.objects.filter(equipement_installe=equipement_id)
    # inst_id = Installation.objects.get(id=equipement_installe.installation_equipement.id)
    # insID= Equipement.objects.filter(id=equipement_installe.installation_equipement.id).exists()

    # equip_id = Installation.objects.get(id=equipement_installe.id)

    # inst_equip = Installation.equipement_installe
    # installation_equipement:releted_name between equipement and installation
    # check before save data from comment form
    if request.method == 'POST':
        installation_form = EquipInstall(data=request.POST)
        # Atribut_inst = AtributForm(data=request.POST)
        if installation_form.is_valid():
            deja_installe = installation_form.save(commit=False)
            deja_installe.author = request.user
            deja_installe.equipement_installe = equipement_installe
            # Atribut_inst.equipement_installe.etat_equipement='1'
            # Atribut_inst.save()

            deja_installe.save()
            messages.success(
                request, f"Felicitation l'equipemet est bien installer")
            return redirect('equip:detail_equipement', equipement_id)
        # else:
        #     return redirect('equip:detail_equipement', equipement_id)
    else:
        installation_form = EquipInstall()

    context = {
        'title': 'detail equipement',
        'equipement_installe': equipement_installe,
        # 'inst_equip': inst_equip,
        'inst':inst,
        'installation_form': installation_form,
        # 'Atribut_inst':Atribut_inst
        #  'inst_id':inst_id,
        # 'insID':insID,

    }

    return render(request, 'equipement/detail_equipement.html', context)



# modifier equipement
# @login_required(login_url='user_auth:login')
@login_required(login_url='accounts/login')

def EquipementUpdate(request, equipement_id):
    equipement=Equipement.objects.get(id=equipement_id)
    form=EquipementFormm(instance=equipement)

    if request.method == 'POST':
        form=EquipementFormm(request.POST, instance=equipement)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.author = request.user
            myform.save()
            messages.success(
                request, f"L'equipemet du numero  {myform.num_serie} est bien modifier")
            return redirect('equip:detail_equipement',equipement_id)

    context = {
        'title': 'Modifier_equipement',
        'form': form
        }

    return render(request,'equipement/update_equipement.html', context)



# class PostUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
#     model = Equipement
#     template_name = 'equipement/update_equipement.html'
#     form_class = EquipementForm
#
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super().form_valid(form)
#
#     def test_func(self):
#         equip = self.get_object()
#         if self.request.user == equip.author:
#             return True
#         else:
#             return True





# # supprimer equipement
# class EquipementDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
#     model = Equipement
#     success_url = '/table'
#     # equip: table_equipement
#     def test_func(self):
#         equipo= self.get_object()
#         if self.request.user == equipo.author:
#             return True
#         else:
#             return True

# delet equipement
@login_required(login_url='accounts/login')
@allowed_users(allowed_roles=['admin'])

def EquipementDeleteView(request, equipement_id):
    equipement=Equipement.objects.get(id=equipement_id)
    if request.method == 'POST':
        equipement.delete()
        messages.success(
            request, f"Felicitation l'equipemet avec numero  {equipement.num_serie} est bien supprimer")
        return redirect('equip:table_equipement')

    context = {
        'title': 'Supprimer_equipement',
        'equipement': equipement
        }

    return render(request,'equipement/equipement_confirm_delete.html', context)


@login_required(login_url='accounts/login')
def table_equipement(request):
    list_quip=Equipement.objects.all()
    # filters
    filter = EquipementFilter(request.GET, queryset=list_quip)
    list_quip = filter.qs
    context={
       'title':'Table_des_equipement',
        'list_quip':list_quip,
        'filter': filter,

    }
    return render(request,'equipement/table_equip.html',context)

#view cataegorie equipement
@login_required(login_url='accounts/login')
def category_table(request):
    list_cat=Category.objects.all()
    list_direction = Direction.objects.all()
    context={
       'title':'Categorie des equipements et les directions',
        'list_cat':list_cat,
        'list_direction': list_direction
    }
    return render(request,'equipement/category_table.html',context)


#add categorie equipement
@login_required(login_url='accounts/login')

def CategorietCreate(request):
    if request.method == 'POST':
        form = CategorieForm(request.POST)
        if form.is_valid():
            myform=form.save()
            messages.success(
                request, f"Felicitations la categorie  {myform.name}  est bien ajoute")
            return redirect(reverse('equip:add_categorie'))
    else:
        form = CategorieForm()

    context = {
        'title': "Categorie D'equipement",
        'form':form,

    }
    return render(request, 'equipement/add_categorie.html', context)

#edit categorie equipement
@login_required(login_url='accounts/login')

def CategoryUpdate(request, categorie_id):
    category=Category.objects.get(id=categorie_id)
    form=CategorieForm(instance=category)

    if request.method == 'POST':
        form=CategorieForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(
                request, f"Felicitation categorie {category.name} est bien modifier")
            return redirect('equip:category_table')

    context = {
        'title': 'Modifier_categorie',
        'form': form
        }

    return render(request,'equipement/update_categorie.html', context)




#direction
@login_required(login_url='accounts/login')

def DirectionCreate(request):
    if request.method == 'POST':
        form = DirectionForm(request.POST)
        if form.is_valid():
            myform=form.save()
            messages.success(
                request, f"Felicitation nom de la direction  {myform.Nom} est bien ajoute")
            return redirect(reverse('equip:add_direction'))

equipement/templates/equipement/category_table.html
{% extends 'base.html'%}
{% block content %}

  <div class="content-wrapper">

        <div class="container-fluid">

            <!--page title-->
            <div class="page-title mb-4 d-flex align-items-center">
                <div class="mr-auto">
                    <h4 class="weight500 d-inline-block pr-3 mr-3 border-right">Tables Categorie & Direction</h4>
                    <nav aria-label="breadcrumb" class="d-inline-block ">
                        <ol class="breadcrumb p-0">
                             <li class="breadcrumb-item"><a href="{% url 'equip:home' %}">Accueil</a></li>
                              <li class="breadcrumb-item"><a href="{% url 'equip:table_equipement' %}">TableEquipement</a></li>
                               <li class="breadcrumb-item"><a href="{% url 'installation:table_installation' %}">TableInstallation</a></li>
                            <li class="breadcrumb-item active" aria-current="page">TableCategorie&Direction</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!--/page title-->
                               {% if messages %}
                                 {% for message in messages %}
                                     <div class="alert alert-{{message.tags}}">
                                        {{message}}
                                     </div>
                                 {% endfor %}
                               {% endif %}

            <div class="row">
                <div class="col-xl-6 col-md-6">
                    <div class="card card-shadow mb-4">


                        <div class="card-header border-0">
                            <div class="custom-title-wrap bar-primary">
                                <div class="custom-title">Categorie D'equipement</div>
                            </div>
                        </div>


                        <ul type="none" class="object-tools">

                              <li>

                                <a href="{% url 'equip:add_categorie' %}" title="Ajouter Categorie D'equipement" class="btn btn-primary p-1">
                                    Add categorie  <big>+</big>
                                </a>

                              </li>



                       </ul>

                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Nom</th>

                                    <th scope="col">Action</th>


                                </tr>
                                </thead>
                                <tbody>
                                {% for list in list_cat %}
                                <tr>
                                    <th scope="row">{{ list.id }}</th>
                                    <td>{{ list.name}}</td>

                                    <td>  <a class="text-dark btn btn-success p-2" href="{% url 'equip:update_categorie' list.id %}" title="Modifier categorie"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></td>


                                </tr>



                                {% endfor%}


                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>

<!--                deuxieme table-->

                <div class="col-xl-6 col-md-6">

                    <div class="card card-shadow mb-4">
                        <div class="card-header border-0">
                            <div class="custom-title-wrap bar-warning">
                                <div class="custom-title">Direction</div>
                            </div>
                        </div>

                        <ul type="none" class="object-tools">
                              <li>

                                <a href="{% url 'equip:add_direction' %}"  title="Ajouter nom d'une direction" class="addlink btn btn-primary p-1">
                                    Add direction  <big>+</big>
                                </a>
                              </li>
                       </ul>


                        <div class="card-body">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                     <th scope="col">Nom</th>


                                    <th scope="col">Action</th>


                                </tr>
                                </thead>
                                <tbody>
                                {% for list in list_direction %}
                                        <tr>
                                            <th scope="row">{{ list.id }}</th>
                                               <td>{{ list.Nom }}</td>


                                            <td><a class="text-dark btn btn-success p-2" href="{% url 'equip:update_direction' list.id %}" title="Modifier direction"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></td>


                                        </tr>
                                 {% endfor %}


                                </tbody>
                            </table>
                        </div>
                    </div>



                </div>
            </div>

        </div>
 {% include 'equipement/include_footer.html' %}


    </div>


{% endblock %}

equipement/templates/equipement/include_footer.html
     <!--footer-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <small>Copyright &copy; VectorLab {% now 'Y' %}</small>
                </div>
            </div>
        </footer>
        <!--/footer-->

equipement/templates/equipement/table_equip.html
{% extends 'base.html'%}
{% block content %}
{% load bootstrap4 %}

{% load crispy_forms_tags %}

<div class="content-wrapper">

        <div class="container-fluid">

            <!--page title-->
            <div class="page-title mb-4 d-flex align-items-center">
                <div class="mr-auto">
                    <h4 class="weight500 d-inline-block pr-3 mr-3 border-right">Table Equipement</h4>
                    <nav aria-label="breadcrumb" class="d-inline-block ">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a href="{% url 'equip:home' %}">Accueil</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'installation:table_installation' %}">TableInstallation</a></li>
                            <li class="breadcrumb-item active" aria-current="page">TableEquipement</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!--/page title-->

            <div class="row">
                <div class="col-xl-12">
                    <div class="card card-shadow mb-4">
                        <div class="card-header border-0">

                            <div class="custom-title-wrap bar-primary">


                                <div class="custom-title">Equipement</div>
                            </div>
                             <div class=" widget-action-link">
                                        <div class="row">
                                        <div class="dropdown" style="margin-right: 15px">
                                            <a href="#" class="btn btn-transparent text-secondary dropdown-hover p-0" data-toggle="dropdown">
                                                Filter <i class="fa fa-caret-down pl-2"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right vl-dropdown">
                                                <form method="get">
                                                     {%  bootstrap_form filter.form %}
                                                     <button type="submit"  class="btn btn-purple float-right"  >
                                                     Recherche
                                                     </button>
                                                </form>
                                            </div>
                                        </div>
                                        </div>

                                    </div>

                            {% if messages %}
                                {% for message in messages %}
                                 <div class="alert alert-{{message.tags}}">
                                    {{message}}
                                 </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <ul type="none" class="object-tools">

                              <li>

                                <a href="{% url 'equip:add_equipement' %} " title="Ajouter Equipement"  class="addlink btn btn-primary p-1">
                                    Add equipement <big>+</big>
                                </a>
                              </li>

                       </ul>
                        <div class="card-body- pt-3 pb-4">
                            <div class="table-responsive">
                                <table id="data_table" class="table table-bordered table-striped" cellspacing="0">

                                    <thead>

                                    <tr>
                                        <th>Num serie</th>
                                        <th>Nom</th>
                                        <th>Date</th>
                                        <th>Categorie</th>
                                         <th>Etat service</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tfoot>

                                    <tr>
                                        <th>Num serie</th>
                                        <th>Nom</th>
                                        <th>Date</th>
                                        <th>Categorie</th>
                                         <th>Etat service</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>
                                    {% for  list in list_quip  %}
                                    <tr>
                                        <td>{{ list.num_serie }}</td>
                                        <td>{{ list.nom }}</td>
                                        <td>{{ list.date_ajoute|date:'d M o' }}</td>
                                        <td>{{ list.category}}</td>
                                         <td>
                                             {% if list.installation_equipement %}
                                                {{ list.installation_equipement.service}}
                                            {% else%}
                                                 Non attribut
                                            {% endif%}


                                        </td>
                                        <td>
                                            {% if list.installation_equipement %}
                                                <center> <button class="btn  btn-success p-1 btn-md">A</button></center>
                                            {% else%}
                                                 <center> <button class="btn  btn-danger p-1 btn-md">N</button></center>
                                            {% endif%}
                                        </td>

                                         <td>


                                              <a class="text-dark btn btn-outline-info p-2" href="{% url 'equip:detail_equipement' list.id %}" title="View equipement"><i class="fa fa-eye" aria-hidden="true"></i></a>



                                              <a class="text-dark btn btn-outline-primary p-2 btn-md" href="{% url 'equip:update_equipement' list.id %}" title="Modifier equipement"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                                {% if request.user.is_staff %}
                                               <a class="btn btn-outline-danger p-2 btn-md " href="{% url 'equip:delete_equipement' list.id %}" title="Supprimer equipement" >  <i class="fa fa-trash-o" aria-hidden="true"></i>  </a>
                                              {% endif %}
                                               {% if list.installation_equipement %}


                                             <a class="text-dark btn btn-outline-success p-2 btn-md " title="Modifier installation" href="{% url 'install:update_installation' list.installation_equipement.id %}" ><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                                 {% if request.user.is_staff %}

                                             <a class="text-dark btn btn-outline-warning p-2 btn-md " href="{% url 'install:update_service' list.installation_equipement.id %}" title="Suivre etat service"><i class="fa fa-bandcamp" aria-hidden="true"></i></a>
                                              {% endif%}



                            {% endif%}


                                         </td>
                                    </tr>
                                  {% empty %}
                                      <tr>
                                        <td colspan="7" class="text-center bg-warning "> Aucun enregistrement</td>
                                    </tr>
                                 {% endfor %}

                                    </tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
<!--    footer -->
     {% include 'equipement/include_footer.html' %}



    </div>

{% endblock content %}