equipement/urls.py
from django.urls import path
from . import views
from .views import EquipementDeleteView

app_name='equipement'

urlpatterns = [
    path('',views.home,name='home'),
    path('table/',views.table_equipement,name='table_equipement'),

    #equipement
    path('add_equipement/' ,views.EquipementCreate,  name='add_equipement'),
    path('detail_equipement/<int:equipement_id>/', views.EquipementDetail, name='detail_equipement'),
    path('update_equipement/<int:equipement_id>/update', views.EquipementUpdate, name='update_equipement'),
    # path('update_equipement/slug:pk>/update', views.PostUpdateView.as_view(), name='update_equipement'),
    path('detail_equipement/<int:equipement_id>/delete/', views.EquipementDeleteView, name='delete_equipement'),
    # path('detail_equipement/<slug:pk>/delete/', EquipementDeleteView.as_view(), name='delete_equipement'),
    # fin equipement

    #categorie
    path('category_table/', views.category_table, name='category_table'),
    path('add_categorie/', views.CategorietCreate, name='add_categorie'),
    path('update_categorie/<int:categorie_id>/update', views.CategoryUpdate, name='update_categorie'),

    #direction
    path('add_direction/', views.DirectionCreate, name='add_direction'),
    path('update_direction/<int:direction_id>/update', views.DirectionUpdate, name='update_direction'),

    path('table_user', views.tableuser, name='table_user'),

]

installation/urls.py
from django.urls import path
from . import views
from .views import InstallationDeleteView

app_name='installation'

urlpatterns = [
    path('table_installation/',views.table_installation,name='table_installation'),
    path('install/',views.InstallationCreate,name='add_install'),
    path('detail_installation/<int:installation_id>/', views.InstallationDetail, name='detail_installation'),
    # path('detail_installation/<slug:pk>/delete/', InstallationDeleteView.as_view(), name='delete_installation'),
    path('update_installation/<int:installation_id>/update', views.InstallationUpdate, name='update_installation'),
    path('detail_installation/<int:installation_id>/delete/', views.InstallationDeleteView, name='delete_installation'),
    #suive service
    path('update_service/<int:service_id>/update', views.ServiceUpdate, name='update_service'),



]

project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings




urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('admin/', admin.site.urls),
    path('', include('equipement.urls',namespace='equip')),
    path('', include('installation.urls',namespace='install')),
    
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

installation/models.py
from django.contrib.auth.models import User
from django.db import models

from equipement.models import Equipement
from macaddress.fields import MACAddressField
# Create your models here.
from django.utils import timezone


SERVICE_ETAT=(
    ('En service','En service'),
    ('En panne','En panne'),
)


class Installation(models.Model):
    ip=models.GenericIPAddressField(max_length=20)
    mac=MACAddressField(verbose_name='Adesse Mac')
    date_installe=models.DateTimeField(null=False,blank=False)
    Nom_direction = models.ForeignKey('Direction', on_delete=models.CASCADE, related_name='nomD')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    equipement_installe = models.OneToOneField(Equipement, on_delete=models.CASCADE, related_name='installation_equipement')
    service = models.CharField(max_length=15, choices=SERVICE_ETAT, default='En service')


    def __str__(self):
        return 'Ip: {} - Mac: {}'.format(self.ip, self.mac)




class Direction(models.Model):
    Nom = models.CharField(max_length=20)

    def __str__(self):
        return '{}'.format(self.Nom)

installation/forms.py
from django import forms
from django.forms import DateInput

from .models import Installation

class DateInput(forms.DateInput):
    input_type = 'date'

class InstallationForm(forms.ModelForm):

    class Meta:
        model = Installation
        fields = ['ip','mac','date_installe','Nom_direction']
        widgets = {
            'date_installe': DateInput()
        }

    def clean_ip(self):
        cd = self.cleaned_data
        if (Installation.objects.filter(ip=cd['ip']).exists()):
            raise forms.ValidationError(f" Ip { cd['ip']}   deja existe ")
        return cd['ip']

    def clean_mac(self):
        cd = self.cleaned_data
        if (Installation.objects.filter(mac=cd['mac']).exists()):
            raise forms.ValidationError(f" Adresse mac {cd['mac']}   deja existe ")
        return cd['mac']





class InstallationFormm(forms.ModelForm):

    class Meta:
        model = Installation
        fields = ['ip','mac','date_installe','Nom_direction']
        widgets = {
            'date_installe': DateInput()
        }


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Installation
        fields = ['service',]

installation/views.py
# ajoute un equipement
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.generic import DeleteView

from accounts.decorators import allowed_users
from equipement.models import Equipement, Category
from installation.forms import InstallationForm, InstallationFormm, ServiceForm
from installation.models import Installation




# table installation
@login_required(login_url='accounts/login')
def table_installation(request):
    list_installation=Installation.objects.all()
    # list_installation_direction = Installation.objects.filter()
    context={
       'title':'Table des installation',
        'list_installation':list_installation,
        # 'list_installation_direction':list_installation_direction,
    }
    return render(request,'installation/table_installation.html',context)



#add installation
@login_required(login_url='accounts/login')

def InstallationCreate(request):
    if request.method == 'POST':
        form = InstallationForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.author = request.user
            myform.save()
            messages.success(
                request, f"Felicitations votre ajout  est bien ajoute")
            return redirect(reverse('install:add_install'))
    else:
        form = InstallationForm()

    context = {
        'title': 'Detail Installation',
        'form':form,

    }

    return render(request, 'installation/add_installation.html', context)


#edit installation
@login_required(login_url='accounts/login')

def InstallationUpdate(request, installation_id):
    installation=Installation.objects.get(id=installation_id)
    form=InstallationFormm(instance=installation)

    if request.method == 'POST':
        form=InstallationFormm(request.POST, instance=installation)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.author = request.user
            myform.save()
            messages.success(
                request, f"Felicitation l'info d'installation avec mac adresse du numero  {myform.mac} est bien modifier")
            return redirect('install:detail_installation',installation_id)

    context = {
        'title': 'Modifier_info_installation',
        'form': form,
        'installation':installation,
        }

    return render(request,'installation/update_installation.html', context)

#Etat service update
@login_required(login_url='accounts/login')
@allowed_users(allowed_roles=['admin'])
def ServiceUpdate(request, service_id):
    installation=Installation.objects.get(id=service_id)
    form=ServiceForm(instance=installation)

    if request.method == 'POST':
        form=ServiceForm(request.POST, instance=installation)
        if form.is_valid():

            form.save()

            messages.success(
                request, f"Felicitation l'etat du service equipemnet est bien mise a jour")
            return redirect('install:detail_installation',service_id)

    context = {
        'title': 'Etat_service',
        'form': form,
        'installation':installation,
        }

    return render(request,'installation/update_service.html', context)





# delet installation
@login_required(login_url='accounts/login')

def InstallationDeleteView(request, installation_id):
    installation=Installation.objects.get(id=installation_id)
    if request.method == 'POST':
        installation.delete()
        messages.success(
            request, f"Felicitation l'equipemet avec numero  {installation.equipement_installe.num_serie} est bien desinstaller")
        return redirect('equip:detail_equipement', installation.equipement_installe.id)

    context = {
        'title': 'Desintaller_equipement',
        'installation': installation
        }

    return render(request,'installation/installation_confirm_delete.html', context)


# detail installation
@login_required(login_url='accounts/login')
def InstallationDetail(request, installation_id):
    detail_installation = get_object_or_404(Installation, pk=installation_id)
    # equipement_installe = Equipement.objects.filter(equipement_id=inst)
    # nstallations = equipement_installe.installation_equipement

    context = {
        'title': 'detail installation',

        'detail_installation':detail_installation,
        # 'nstallations':nstallations,

        # 'equipement_installe':equipement_installe,

    }

    return render(request, 'installation/detail_installation.html', context)








# def InstallationDetail(request, equipement_id):
#     equipement_installe= get_object_or_404(Equipement, pk=equipement_id)
#     inst= Installation.objects.filter(equipement_installe=equipement_id)
#     nstallations = equipement_installe.installation_equipement
#
#
#     context = {
#         'title': 'detail installation',
#
#         'inst':inst,
#         'nstallations':nstallations,
#
#         'equipement_installe':equipement_installe,
#
#     }
#
#     return render(request, 'equipement/detail_installation.html', context)




# # detail_equipement/<int:equipement_id>/
# #supprimer installation
# class InstallationDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
#     model = Installation
#     success_url = '/table_installation'
#     def test_func(self):
#         inst= self.get_object()
#         if self.request.user == inst.author:
#             return True
#         else:
#             return True

installation/templates/installation/add_installation.html
{% extends 'base.html'%}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">

  <!-- Trigger the modal with a button -->
<!--  <button type="button" class="btn btn-info p-2 btn-md" data-toggle="modal" data-target="#myModal" title="Ajouter Equipement">+</button>-->

  <!-- Modal -->
<!--  <div class="modal fade" id="myModal" role="dialog">-->
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" >Detail D'installation</h4>

                   <button type="button" class="close" data-dismiss="modal">&times;</button>


        </div>
        <div class="modal-body">
               {% if messages %}
                 {% for message in messages %}
                     <div class="alert alert-{{message.tags}}">
                        {{message}}
                     </div>
                 {% endfor %}
               {% endif %}
          <!--    form      -->
      <form method="POST" >
           {% csrf_token %}
           {{form|crispy}}


                  <div class="mt-6">
                       <button type="submit" class="btn btn-primary p-2 pl-4 pr-4">Add</button>
                    <button type="reset" class="btn btn-outline-secondary p-2">Cancel</button>
                  </div>

      </form>
        </div>
        <div class="modal-footer">

                       <button type="button" class="btn btn-default p-2 " data-dismiss="modal"> Close </button>

        </div>


          <!--   endform         -->
      </div>
    </div>
<!--  </div>-->
</div>

{%  endblock  %}

installation/templates/installation/detail_installation.html
{% extends 'base.html'%}
{% block content %}
{% load crispy_forms_tags %}




    <div class="content-wrapper">

        <div class="container-fluid">

            <!--page title-->
            <div class="page-title mb-4 d-flex align-items-center">
                <div class="mr-auto">
                    <h4 class="weight500 d-inline-block pr-3 mr-3 border-right">View Installation</h4>
                    <nav aria-label="breadcrumb" class="d-inline-block ">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a href="{% url 'equip:home' %}">Accueil</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'equip:table_equipement' %}">TableEquipement</a></li>
                             <li class="breadcrumb-item"><a href="{% url 'installation:table_installation' %}">TableInstallation</a></li>
                            <li class="breadcrumb-item active" aria-current="page">View {{detail_installation.equipement_installe.nom}}</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!--/page title-->

            <div class="row">
                <div class="col-xl-9">
                    <div class="card card-shadow mb-4">
                        <div class="card-header border-0">
                            <div class="custom-title-wrap bar-primary">
                                <div class="custom-title">

                                     <button class="btn  btn-success p-1 btn-md"></button>
                                     Installation<br>
                                    Etat service: {{detail_installation.service}}
                                </div>



                            </div>
                               <div >


                                </div>
                        </div>

                        <div class="card-body">

                            <div class="row">
                                <div class="col-md-6 mb-2">
                                  <ul>
                                      <li> Ip: {{detail_installation.ip}} </li>
                                      <li>Adesse mac: {{detail_installation.mac}}   </li>
                                      <li>  Atribué au direction: {{detail_installation.Nom_direction}}</li>
                                       <li>  Installer par: {{detail_installation.author}}</li>
                                        <li>  Date d'installation: {{detail_installation.date_installe|date:'d M o'}}</li>

                                  </ul>


                                             <ul type="none" class="object-tools">
                                              <li>


                                                <a href="{% url 'installation:delete_installation' detail_installation.id %}"
                                                  title="Desinstaller un equipement" class="addlink btn btn-danger p-2 mt-5">
                                                   Desinstaller
                                                </a>

                                              </li>
                                             </ul>




                                    <!-- Modal -->

                                </div>

                                <div class="col-md-4 mb-6">
                            <ul>
                                 <li> Nom equipement: {{detail_installation.equipement_installe.nom}} </li>
                                <li> Numero serie: {{detail_installation.equipement_installe}} </li>
                                <li> Category: {{detail_installation.equipement_installe.category}} </li>
                                <li> Ajouter par: {{detail_installation.equipement_installe.author}} </li>
                                <li> Ajouter par: {{detail_installation.equipement_installe.date_ajoute|date:'d M o'}}</li>



                            </ul>

                                    <!-- Modal -->


                                </div>



                            </div>



                        </div>
                    </div>
                </div>


            </div>

        </div>

        <!--footer-->



        <!--/footer-->
    </div>
    <!--/main content wrapper-->



{% endblock  %}

installation/templates/installation/installation_confirm_delete.html
{% extends 'base.html'%}
{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="exampleModalLabel">Desinstaller Un Equipement</h4>

                    <button type="button" class="close" data-dismiss="modal">
                       <a href="{% url 'installation:detail_installation' installation.id %}" >&times;</a>
                   </button>



        </div>
          <div class="modal-body">
                      <!--    form      -->

    <form method="POST">

        <p class="p-0 d-inline-block "> Voulez vous vraiment desinstaller cette equipement  ? </p>
        <ul>
            <li>Nom equipement:  {{installation.equipement_installe.nom}}</li>
            <li>Numero serie:  {{installation.equipement_installe}}</li>
            <li>Category: {{installation.equipement_installe.category}}</li>
            <li>Ip: {{installation.ip}}</li>
            <li> Adresse mac:  {{installation.mac}}</li>
             <li> Atribué au direction: {{installation.Nom_direction}}</li>
        </ul>
        {% csrf_token %}
        <input class="btn btn-danger mt-3 p-2" type="submit" value="Oui">
        <a class="btn btn-secondary mt-3 back-btn p-2" href="{% url 'installation:detail_installation' installation.id %}">Non</a>
    </form>
          </div>



        <div class="modal-footer">
              <a href="{% url 'installation:detail_installation' installation.id %}" >
                         <button type="button" class="btn btn-default p-2 " data-dismiss="modal">
                         Close
                        </button>
              </a>



        </div>


          <!--   endform         -->
      </div>
    </div>
<!--  </div>-->
</div>

{%  endblock  %}

installation/templates/installation/table_installation.html
{% extends 'base.html'%}
{% block content %}

{% load crispy_forms_tags %}
<div class="content-wrapper">

        <div class="container-fluid">

            <!--page title-->
            <div class="page-title mb-4 d-flex align-items-center">
                <div class="mr-auto">
                    <h4 class="weight500 d-inline-block pr-3 mr-3 border-right">Table Installation</h4>
                    <nav aria-label="breadcrumb" class="d-inline-block ">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a href="{% url 'equip:home' %}">Accueil</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'equip:table_equipement' %}">TableEquipement</a></li>
                            <li class="breadcrumb-item active" aria-current="page">TableInstallation</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!--/page title-->

            <div class="row">
                <div class="col-xl-12">
                    <div class="card card-shadow mb-4">
                        <div class="card-header border-0">

                            <div class="custom-title-wrap bar-primary">

                                <div class="custom-title">Detail Installation</div>
                                {% if messages %}
                                {% for message in messages %}
                                 <div class="alert alert-{{message.tags}}">
                                    {{message}}
                                 </div>
                                {% endfor %}
                            {% endif %}
                            </div>
                        </div>
                        <div class="card-body- pt-3 pb-4">
                            <div class="table-responsive">
                                <table id="data_table" class="table table-bordered table-striped" cellspacing="0">

                                    <thead>

                                    <tr>

                                        <th>Num serie </th>
                                        <th>Nom  </th>
                                        <th>Categorie </th>

                                        <th>Direction</th>
                                         <th>Date d'installation</th>

                                        <th>Etat service</th>


                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tfoot>

                                    <tr>

                                        <th>Num serie </th>
                                        <th>Nom  </th>
                                        <th>Categorie </th>

                                        <th>Direction</th>
                                        <th>Date d'installation</th>

                                        <th>Etat service</th>


                                        <th width="100px">Action</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>
                                    {% for  list in list_installation  %}
                                    <tr>

                                        <td>{{ list.equipement_installe}}</td>
                                        <td>{{ list.equipement_installe.nom}}  </td>
                                        <td>{{ list.equipement_installe.category}} </td>

                                         <td>{{ list.Nom_direction }}</td>
                                        <td>{{ list.date_installe|date:'d M o' }}</td>


                                        <td>
                                           {{ list.service}}

                                        </td>
                                         <td>
                                                 <a class="text-dark  btn btn-outline-info p-2 btn-md " href="{% url 'install:detail_installation' list.id %}" title="View equipement"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                              {% if request.user.is_staff %}
                                                 <a class="text-dark btn btn-outline-warning p-2 btn-md " href="{% url 'install:update_service' list.id %}" title="Suivre etat service"><i class="fa fa-bandcamp" aria-hidden="true"></i></a>
                                                {% endif %}
                                               <a class="text-dark  btn btn-outline-success p-2 btn-md " href="{% url 'install:update_installation' list.id %}" title="Modifier installation"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>

                                         </td>
                                    </tr>
                                 {% endfor %}
                                    </tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
<!--    footer -->
     {% include 'equipement/include_footer.html' %}


    </div>

{% endblock content %}

installation/templates/installation/update_installation.html
{% extends 'base.html'%}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">

  <!-- Trigger the modal with a button -->
<!--  <button type="button" class="btn btn-info p-2 btn-md" data-toggle="modal" data-target="#myModal" title="Ajouter Equipement">+</button>-->

  <!-- Modal -->
<!--  <div class="modal fade" id="myModal" role="dialog">-->
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" >Modifier detail d'installation</h4>

            <button type="button" class="close" data-dismiss="modal">
                       <a href="{% url 'equip:table_equipement' %}"  >&times;</a>
            </button>


        </div>
        <div class="modal-body">
               {% if messages %}
                 {% for message in messages %}
                     <div class="alert alert-{{message.tags}}">
                        {{message}}
                     </div>
                 {% endfor %}
               {% endif %}
          <!--    form      -->
      <form method="POST" >
           {% csrf_token %}
           {{form|crispy}}


                  <div class="mt-6">
                       <button type="submit" class="btn btn-primary p-2 pl-4 pr-4">Valider</button>
                    <button type="reset" class="btn btn-outline-secondary p-2">Cancel</button>
                  </div>

      </form>
        </div>
        <div class="modal-footer">

<!--            install:detail_installation' installation.id-->
            <a href="{% url 'equip:table_equipement' %}"  >
                       <button type="button" class="btn btn-default p-2 " data-dismiss="modal">
                          Close
                       </button>
            </a>

        </div>


          <!--   endform         -->
      </div>
    </div>
<!--  </div>-->
</div>

{%  endblock  %}

installation/templates/installation/update_service.html
{% extends 'base.html'%}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">

  <!-- Trigger the modal with a button -->
<!--  <button type="button" class="btn btn-info p-2 btn-md" data-toggle="modal" data-target="#myModal" title="Ajouter Equipement">+</button>-->

  <!-- Modal -->
<!--  <div class="modal fade" id="myModal" role="dialog">-->
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" >Mise a jour cet equipement qui est "{{installation.service}}"  </h4>

            <button type="button" class="close" data-dismiss="modal">
<!--                install:detail_installation' installation.id -->
                       <a href="{% url 'equip:table_equipement' %}"  >&times;</a>
            </button>


        </div>
        <div class="modal-body">
               {% if messages %}
                 {% for message in messages %}
                     <div class="alert alert-{{message.tags}}">
                        {{message}}
                     </div>
                 {% endfor %}
               {% endif %}

          <table>
              <tr>
                  <td>
                           <li> Nom equipement: {{installation.equipement_installe.nom}} </li>
                                <li> Numero serie: {{installation.equipement_installe}} </li>
                                <li> Categorie: {{installation.equipement_installe.category}} </li>
                                <li> Ajouter par: {{installation.equipement_installe.author}} </li>
                                <li> Date ajoute: {{installation.equipement_installe.date_ajoute|date:'d M o'}}</li>

                  </td>
                  <td></td><td></td> <td></td><td></td>
                  <td>
                          <li> Ip: {{installation.ip}} </li>
                                      <li>Adesse mac: {{installation.mac}}   </li>
                                      <li>  Atribué au direction: {{installation.Nom_direction}}</li>
                                       <li>  Installer par: {{installation.author}}</li>
                                        <li>  Date d'installation: {{installation.date_installe|date:'d M o'}}</li>
                  </td>
              </tr>
          </table>
        <br><br>
          <!--    form      -->
      <form method="POST" >
           {% csrf_token %}
           {{form|crispy}}


                  <div class="mt-6">
                       <button type="submit" class="btn btn-primary p-2 pl-4 pr-4">Valider</button>
                    <button type="reset" class="btn btn-outline-secondary p-2">Cancel</button>
                  </div>

      </form>
        </div>
        <div class="modal-footer">

            <a href="{% url 'equip:table_equipement' %}"  >
                       <button type="button" class="btn btn-default p-2 " data-dismiss="modal">
                          Close
                       </button>
            </a>

        </div>


          <!--   endform         -->
      </div>
    </div>
<!--  </div>-->
</div>

{%  endblock  %}